name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.44e2bf8a-8c26-4e2d-89b4-a0a9cb51c4a9}}
          GH_TOKEN: ${{ secrets.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 }}
          

          
